

% These are the PTCHD1 KO data
files = {
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-KO\ACtx\KeC31\102920\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-KO\MGB\KeC24\100620\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-KO\MGB\KeC24\100720\paired_pulse_noisebursts\'; ...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-KO\MGB\KeC28\101420\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-KO\MGB\KeC30\101920\paired_pulse_noisebursts';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-KO\MGB\KeC31\102920\paired_pulse_noisebursts'};


% These are the PTCHD1 WT data
files_wt = {
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\ACtx\KeC32\110220\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\ACtx\KeC33\110620\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\ACtx\KeC35\111320\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\ACtx\KeC35\111420\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\MGB\KeC23\100120\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\MGB\KeC23\100220\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\MGB\KeC27\100820\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\MGB\KeC29\101520\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\MGB\KeC32\110120\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\MGB\KeC32\110220\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\MGB\KeC32\110320\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\MGB\KeC33\110620\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\MGB\KeC35\111320\paired_pulse_noisebursts\';...
    'E:\Ke_Chen\Processed Data\PTCHD1-Project\PTCHD1-WT\MGB\KeC35\111420\paired_pulse_noisebursts\'};

files_all = [files; files_wt];

%% decoding with statistic inferences
addpath('E:\Ke_Chen\MATLAB\Ephys-analysis\NeuralDecoder')
for j = 1:length(files_all)
    cd(files_all{j})
    load('summary.mat')
    for i = 1: length(spikedata)
        if spikedata(i).keep ==1 && spikedata(i).resp == 1
            fprintf('Processing neuron # %d of total %d\n', i, length(spikedata))
            try
                data = summary(i);
                [results, options] = SU_decoding_PSTH(data);
                spikedata(i).decoding.results = results;
                spikedata(i).decoding.options = options;
            catch
                continue
            end
        end
    end
%     save('summary_decoding_stats.mat','spikedata')
    save('summary_decoding_stats.mat', 'spikedata', 'summary', 'decoding_results')
end