%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% Analysis Starts From Here %%%%%%%%%%%%%%%%%%%%%%%
%% summarize the pupil size data
% This part and the next part are very important;
clear
ko_file = {'KeC22-Session2.mat'; 'KeC24-Session1.mat'; 'KeC28-Session1-run1.mat';...
    'KeC31-Session3-run1.mat';'KeC34-Session2-run1.mat'; 'KeC37-Session3-Run1.mat';...
    'KeC39-Session3-Run1.mat'; 'KeC41-Session5-Run1.mat'; 'KeC45-Session6-Run1.mat';...
    'KeC49-Session6-Run1.mat'; 'KeC50-Session6-Run1.mat'};
% temp = [];

% Let's create a relative smaller summary file
cd('E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\Pupil_analysis\Summary')
for i = 1:length(ko_file)
    load(ko_file{i})
    summary(i).filename = Tosca.filename;
    summary(i).genotype = 'ko';
    summary(i).pupil_area = Tosca.pupil_area_correct;
    summary(i).video_summary = Tosca.video_summary;
    summary(i).time          = Tosca.time;
    summary(i).event_time    = Tosca.event_time;
    summary(i).level         = Tosca.level;
end
cd('E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\Pupil_analysis')
save('summary_ko.mat', 'summary', 'ko_file', '-v7.3')
%
%
%
clear summary
wt_file = {'KeC23-Session2.mat'; 'KeC25-Session1-Run1.mat'; 'KeC27-Session1-Run1.mat';...
    'KeC29-Session1-run1.mat';'KeC33-Session1-Run2';'KeC35-Session1-Run1.mat';...
    'KeC36-Session3-Run1.mat'; 'KeC38-Session3-Run1.mat'; 'KeC40-Session5-Run1.mat';...
    'KeC43-Session5-Run1.mat'; 'KeC44-Session6-Run1.mat'; 'KeC46-Session7-Run1.mat';...
    'KeC47-Session6-Run1.mat'; 'KeC48-Session6-Run1.mat'};
% Let's create a relative smaller summary file
cd('E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\Pupil_analysis\Summary')
for i = 1:length(wt_file)
    load(wt_file{i})
    summary(i).filename = Tosca.filename;
    summary(i).genotype = 'wt';
    summary(i).pupil_area = Tosca.pupil_area_correct;
    summary(i).video_summary = Tosca.video_summary;
    summary(i).time          = Tosca.time;
    summary(i).event_time    = Tosca.event_time;
    summary(i).level         = Tosca.level;
end
cd('E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\Pupil_analysis')
save('summary_wt.mat', 'summary', 'wt_file', '-v7.3')
%% Let's unwrap the summary files
clear
path = 'E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\Pupil_analysis';
summaryData = summarize_pupil(path);

save('summaryData_all.mat', 'summaryData')

%% plot out the summary data for pupil
load('summaryData_all.mat')
additional_fig = 0;
plots = summary_plot_pupil(summaryData, additional_fig);

%% patch process roi based analysis/noiseburst
% path = {'Z:\KeChen\Analysis\Noiseburst\KeC27';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC29';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC30';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC31';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC32';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC33';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC34\111020';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC34\111220';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC34\111320\noise35';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC34\111320\noise45';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC34\111320\noise55';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC34\111320\noise65';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC34\111320\noise75';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC34\111320\noise85';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC35\111320';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC35\111420';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC35\111520\noise35';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC35\111520\noise45';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC35\111520\noise55';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC35\111520\noise65';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC35\111520\noise75';...
%     'Z:\KeChen\Analysis\Noiseburst\KeC35\111520\noise85'
%     };

% path = {'Z:\KeChen\Analysis\Noiseburst\newVideos\KeC27\100620';...
%     'Z:\KeChen\Analysis\Noiseburst\newVideos\KeC28\100820';...
%     'Z:\KeChen\Analysis\Noiseburst\newVideos\KeC28\100920';
%     'Z:\KeChen\Analysis\Noiseburst\newVideos\KeC29\101620';...
%     'Z:\KeChen\Analysis\Noiseburst\newVideos\KeC30';...
%     'Z:\KeChen\Analysis\Noiseburst\newVideos\KeC31'};
% for i = 1:length(path)
%     fprintf('Processing Video # %d of %d\n', i, length(path))
%     video_analysis_basedROI(path{i})
% end


%% %% batch process roi based analysis/Tosca
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% path = {'Z:\KeChen\Analysis\KeC22\092220';...
%     'Z:\KeChen\Analysis\KeC23\092220';...
%     'Z:\KeChen\Analysis\KeC24\092420';...
%     'Z:\KeChen\Analysis\KeC25\092820';...
%     'Z:\KeChen\Analysis\KeC27\100720';...
%     'Z:\KeChen\Analysis\KeC27\100920';...
%     'Z:\KeChen\Analysis\KeC28\101420';...
%     'Z:\KeChen\Analysis\KeC29\101620';...
%     'Z:\KeChen\Analysis\KeC30\Session1';...
%     'Z:\KeChen\Analysis\KeC31\Session3';...
%     'Z:\KeChen\Analysis\KeC32\Session 3';...
%     'Z:\KeChen\Analysis\KeC33\Session 1';...
%     'Z:\KeChen\Analysis\KeC34\Session 1';...
%     'Z:\KeChen\Analysis\KeC34\Session 2';...
%     'Z:\KeChen\Analysis\KeC35\Session 1';...
%     };

% path = {'Z:\KeChen\Analysis\KeC43\Session5';...
%     'Z:\KeChen\Analysis\KeC44\Session6';...
%     'Z:\KeChen\Analysis\KeC45\Session6';...
%     'Z:\KeChen\Analysis\KeC46\Session7';...
%     'Z:\KeChen\Analysis\KeC47\Session6';...
%     };
% path = {'Z:\KeChen\Analysis\KeC43\Session1';...
%     'Z:\KeChen\Analysis\KeC43\Session2'
%     'Z:\KeChen\Analysis\KeC43\Session3';...
%     'Z:\KeChen\Analysis\KeC43\Session4';...
%     'Z:\KeChen\Analysis\KeC44\Session2';...
%     'Z:\KeChen\Analysis\KeC44\Session3';...
%     'Z:\KeChen\Analysis\KeC44\Session4';...
%     'Z:\KeChen\Analysis\KeC44\Session5';...
%     'Z:\KeChen\Analysis\KeC45\Session2';...
%     'Z:\KeChen\Analysis\KeC45\Session3';...
%     'Z:\KeChen\Analysis\KeC45\Session4';...
%     'Z:\KeChen\Analysis\KeC45\Session5';...
%     'Z:\KeChen\Analysis\KeC46\Session2';...
%     'Z:\KeChen\Analysis\KeC46\Session3';...
%     'Z:\KeChen\Analysis\KeC46\Session4';...
%     'Z:\KeChen\Analysis\KeC46\Session5';...
%     'Z:\KeChen\Analysis\KeC47\Session2';...
%     'Z:\KeChen\Analysis\KeC47\Session3';...
%     'Z:\KeChen\Analysis\KeC47\Session4';...
%     'Z:\KeChen\Analysis\KeC47\Session5';...
%     };
path = {'Z:\KeChen\Analysis\KeC44\Session7';...
    'Z:\KeChen\Analysis\KeC45\Session7'};
for i = 1:length(path)
    fprintf('Processing Video # %d of %d\n', i, length(path))
    video_analysis_basedROI(path{i})
end
%% plot the summary data of the orofacial based on ROI

%% Let's align the ROI changes to different sound intensity for tosca
% clear
% cd('E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\ROIbased_Tosca\data')
% files = dir('*.mat');
% for i = 25:length(files)
%     cd('E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\ROIbased_Tosca\data')
%     filename = files(i).name;
%     video_analysis_align_roi_tosca(filename)
% end

%% summarize the data into a easier plot format
wt_file =  {'KeC23-Session2.mat'; 'KeC25-Session1.mat'; 'KeC27-Session1.mat'; 'KeC29-Session1.mat';...
     'KeC32-Session3.mat'; 'KeC33-Session1.mat'; 'KeC35-Session1.mat';'KeC36-Session3-Run1.mat';...
     'KeC38-Session3-Run1.mat';'KeC40-Session3-Run1.mat'; 'KeC36-Session5-Run1.mat';... 
     'KeC38-Session5-Run1.mat';'KeC40-Session5-Run1.mat'; 'KeC43-Session5-Run1.mat';...
     'KeC44-Session6-Run1.mat'; 'KeC46-Session7-Run1.mat'; 'KeC47-Session6-Run1.mat'; 'KeC48-Session6-Run1.mat'};
 
ko_file = {'KeC22-Session2.mat'; 'KeC24-Session1.mat'; 'KeC28-Session1.mat'; 'KeC31-Session3.mat';...
    'KeC34-Session2.mat';'KeC37-Session3-Run1.mat'; 'KeC39-Session3-Run1.mat';... 
    'KeC41-Session3-Run1.mat'; 'KeC37-Session5-Run1.mat'; 'KeC39-Session5-Run1.mat';... 
    'KeC41-Session5-Run1.mat';'KeC45-Session6-Run1.mat'; 'KeC49-Session6-Run1.mat'; 'KeC50-Session6-Run1.mat'}; 
 
% Pool all the data together

clear summary
cd('E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\ROIbased_Tosca\Summary')
for i = 1:length(wt_file)
    load(wt_file{i})
    summary(i).filename = Tosca.filename;
    summary(i).genotype = 'wt';
    summary(i).orofacial = Tosca.orofacial;
    summary(i).video_summary = Tosca.video_summary;
    summary(i).time          = Tosca.time;
    summary(i).event_time    = Tosca.event_time;
    summary(i).level         = Tosca.level;
end
cd('E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\ROIbased_Tosca')
save('summary_wt.mat', 'summary', 'wt_file', '-v7.3')

clear summary
cd('E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\ROIbased_Tosca\Summary')
for i = 1:length(ko_file)
    load(ko_file{i})
    summary(i).filename = Tosca.filename;
    summary(i).genotype = 'ko';
    summary(i).orofacial = Tosca.orofacial;
    summary(i).video_summary = Tosca.video_summary;
    summary(i).time          = Tosca.time;
    summary(i).event_time    = Tosca.event_time;
    summary(i).level         = Tosca.level;
end
cd('E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\ROIbased_Tosca')
save('summary_ko.mat', 'summary', 'ko_file', '-v7.3')

%% Let's create a relative smaller summary file
% Let's unwrap the summary files
clear
path = 'E:\Ke_Chen\Processed Data\PTCHD1-Project\Video_analysis\ROIbased_Tosca';
summaryData = summarize_orofacial(path);

repeats.ko = {[6, 9], [7, 10], [8,11]};
repeats.wt = {[8, 11], [9, 12], [10, 13]};

save('summaryData_all.mat', 'summaryData', 'repeats')
%% plot out the summary data for Orofacial Movements
clear;close all;clc
load('summaryData_all.mat')
% repeats.ko = {[6, 9], [7, 10], [8,11]};
% repeats.wt = {[8, 11], [9, 12], [10, 13]};
cutOff = 1;
summaryData = spont_movement(summaryData, cutOff);

additional_fig = 0;
plots = summary_plot_orofacial(summaryData, additional_fig, cutOff, repeats);
%% get the baseline orofacial movement
indx = find(summaryData.wt(1).t > -2 & summaryData.wt(1).t < 0);
genotype = {'wt', 'ko'};

%% save data for 2-way anova analysis
% filename = 'summary_Mtrace_anterior.xlsx';
% xlswrite(filename,summary_Mtrace_anterior.wt.peak,1)
% xlswrite(filename,summary_Mtrace_anterior.ko.peak,2)
% 
% filename = 'summary_Mtrace_posterior.xlsx';
% xlswrite(filename,summary_Mtrace_posterior.wt.peak,1)
% xlswrite(filename,summary_Mtrace_posterior.ko.peak,2)
% save('ROI_analysis_Tosca_summary.mat', 'summary_Mtrace_anterior', 'summary_Mtrace_posterior')
%% noiseburst adaptation
edit noiseburst_adaptation
