%% patch process roi based analysis/noiseburst
% add Ephys folder to the searchable list, so that we can cite/use the
% scripts there
addpath('Z:\KeChen\Analysis\Ephys')

%% Add the file you need to process in batch
path = {'Z:\KeChen\Analysis\KeC36\Session 3';...
    'Z:\KeChen\Analysis\KeC36\Session 4';...
    'Z:\KeChen\Analysis\KeC36\Session 5';...
    'Z:\KeChen\Analysis\KeC36\Session 6';...
    'Z:\KeChen\Analysis\KeC37\Session 3';...
    'Z:\KeChen\Analysis\KeC37\Session 4';...
    'Z:\KeChen\Analysis\KeC37\Session 5';...
    'Z:\KeChen\Analysis\KeC37\Session 6'};

%% Automatically process the video files: May take hours to finish 
for i = 1:length(path)
    fprintf('Processing Video # %d of %d\n', i, length(path))
    video_analysis_basedROI(path{i})
end